DROP TABLE IF EXISTS Tarjous;
DROP TABLE IF EXISTS Kauppa CASCADE;
DROP TABLE IF EXISTS TuotteenLuokat;
DROP TABLE IF EXISTS TuoteLuokka CASCADE;
DROP TABLE IF EXISTS Tuote CASCADE;
DROP TABLE IF EXISTS Meklari CASCADE;
DROP TABLE IF EXISTS Asiakas CASCADE;
